### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by akshatarora10** [littlepotato123/Project-Share#56]
Search Bar:
 - More curved borders
- Make it taller and wider
Search by author/category button:
- Move to the left of the search bar
- Make it look like a switch (where a ballpoint moves)
     - Switch should be as tall as the search bar
- Instead of saying search by category or author, use "A" or "C"

**Comment by littlepotato123** [comment]
- I don't think we should put the switch to the left of the input since then the website would be less responsive.
- Could you be more specific as to where you want the round borders?
- I think we should keep the Author or Category and not replace with "A" or "C" since most users would not be able to guess that unless we put another description, but that would take up more space.
   - We could replace with just "Author: " or "Category: " instead of "Search by Author: " or "Search by Category: "

**Comment by littlepotato123** [comment]
Reload the page until the user handle is in the Navigation Bar
